= Terraform Provider for Uptime.com

== Installation and usage

Please see the https://registry.terraform.io/providers/uptime-com/uptime/latest/docs[documentation on the Terraform Registry].

== Rate Limits

Terraform has a tendency to use many API requests when managing a large group of Uptime.com checks. If this becomes a problem, please contact Uptime.com support to request a rate limit increase.

== Credits

Contributions are welcome! Please feel free to fork and submit a pull request with any improvements.

terraform-provider-uptime was originally created by https://github.com/kylegentle[Kyle Gentle], with support from Elias Laham and the Dev Team at Uptime.com.

== Acceptance testing

In order to run acceptance tests Uptime.com API token is required.

    export TF_ACC=1
    export UPTIME_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    go test -v ./uptime/... -run ^TestAcc.+$

In order to get detailed HTTP requests/responses info, set `UPTIME_TRACE` environment variable to `1`.

    export UPTIME_TRACE=1

You can run those in Docker as well.

    cat > .env <<EOF
    TF_ACC=1
    UPTIME_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    EOF
    docker compose up testacc

== Contribution guidelines

TODO
