= Terraform Provider for Uptime.com

== Requirements

* Terraform v0.12.0 or higher
* Go v1.12 or higher (https://go.dev/doc/install[installation instructions])

== Installation

=== Download &amp; build the provider

First, download and build the provider on your local machine:

----
git clone https://github.com/uptime-com/terraform-provider-uptime.git
cd terraform-provider-uptime
go build -o ~/go/bin/terraform-provider-uptime
----

=== Installing

In order for Terraform to use terraform-provider-uptime, it needs to be linked to the plugin directory. Example commands for an OS X Darwin machine:

----
mkdir -p ~/.terraform.d/plugins/darwin_amd64
ln -s ~/go/bin/terraform-provider-uptime ~/.terraform.d/plugins/darwin_amd64/terraform-provider-uptime
----

For Linux machines, follow the OS X process, replacing `darwin` with `linux`.

For a Windows machine, in PowerShell:

[source,powershell]
----
New-Item %APPDATA%\terraform.d\plugins\windows_amd64 -Type 'directory' -Force
cmd /c mklink /d $env:GOPATH\bin\terraform-provider-uptime %APPDATA%\terraform.d\plugins\windows_amd64\terraform-provider-uptime
----

=== Rate Limits

Terraform has a tendency to use many API requests when managing a large group of Uptime.com checks. If this becomes a problem, please contact Uptime.com support to request a rate limit increase.

== Credits

Contributions are welcome! Please feel free to fork and submit a pull request with any improvements.

terraform-provider-uptime was originally created by https://github.com/kylegentle[Kyle Gentle], with support from Elias Laham and the Dev Team at Uptime.com.

=== Contributors

* https://github.com/kylegentle[Kyle Gentle]
* https://github.com/liamkinne[Liam Kinne]

== Resources

(Section is incomplete)

==== uptime_check_ntp

Example:

[source,go]
----
resource "uptime_check_ntp" "google" {
    name = "Google Public NTP"
    address = "time.google.com"
    contact_groups = ["Default", "NTP"]
    interval = 1
    locations = ["US-East", "GBR"]
    tags = ["terraform"]
}
----

Required attributes:

* *address*, _string_: address of the server under test

* *contact_groups*, _list(string)_: contact groups to alert

* *interval*, _number_: time interval between checks, in minutes

* *locations*, _list(string)_: probe server locations

Optional attributes:

* *name*, _string_: human-readable/friendly name

* *tags*, _list(string)_: tags to attach to the check

* *notes*, _string_: arbitrary notes for check

* *include_in_global_metrics*, _bool_: whether to include this check in global uptime metrics

* *ip_version*, _string, limited to "IPV4" or "IPV6"_: IP version to use

* *sensitivity*, _number_: number of probe servers that should detect a failure before an alert is triggered

* *threshold*, _number_: timeout threshold for server response, in seconds

* *port*, _number_: port where service is running

== Acceptance testing

In order to run acceptance tests Uptime.com API token is required.

    export TF_ACC=1
    export UPTIME_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    go test -v ./uptime/... -run ^TestAcc.+$

In order to get detailed HTTP requests/responses info, set `UPTIME_TRACE` environment variable to `1`.

    export UPTIME_TRACE=1

You can run those in Docker as well.

    cat > .env <<EOF
    TF_ACC=1
    UPTIME_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    EOF
    docker compose up testacc

== Contribution guidelines

TODO
